DB_Project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from login import views
from group1 import views
admin.autodiscover()
import os
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DB_Project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('login.urls', namespace="login")),
    url(r'^group1', include('group1.urls', namespace="group1")),
    url(r'^group2', include('group2.urls', namespace="group2")),
    url(r'^group3', include('group3.urls', namespace="group3")),
    url(r'^group4', include('group4.urls', namespace="group4")),
    url(r'^group5', include('group5.urls', namespace="group5")),
    url(r'^group6', include('group6.urls', namespace="group6")),
    url(r'^group7', include('group7.urls', namespace="group7")),
    url(r'^site_media/(?P<path>.*)$',
       'django.views.static.serve',
      {'document_root' : BASE_DIR + '/media'})
)

group1/urls.py
from django.conf.urls import patterns, include, url
from group1 import views

urlpatterns = patterns('',
    url(r'/index/$', views.index, name='index'),
    url(r'/search_file/$', views.search_file, name='search_file'),
    url(r'/send_email/(?P<doc_id>\d+)/$', views.send_email, name='send_email'),
    url(r'/sender/$', views.sender, name='sender'),
    url(r'/add_person/$', views.sender, name='add_person'),
    url(r'/upload_file/$', views.upload_file, name='upload_file'),
    url(r'/edit_file/(?P<doc_id>\d+)/$', views.edit_file, name='edit_file'),
    url(r'/edit_this_file/$', views.edit_this_file, name='edit_this_file'),
    url(r'/add_category/$', views.add_category, name='add_category'),
    url(r'/add_people/$', views.add_people, name='add_people'),
	
)

group2/urls.py
from django.conf.urls import patterns, include, url
from group2 import views

urlpatterns = patterns('',
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^dataStudent/$', views.data_student, name='data_student'),
    url(r'^dataStudentEdit/$', views.data_student_edit, name='data_student_edit'),
    url(r'^getdataStudentEdit/$', views.get_data_student_edit, name='get_data_student_edit'),
    url(r'^search_student/$', views.search_student, name='search_student'),
    url(r'^search_student/profile/(\d+)/$', views.profile_admin, name='profile_admin'),
    url(r'^search_student/regis_result/(\d+)/$', views.regis_result_admin, name='regis_result_admin'),
    url(r'^search_student/viyanipon_admin/(\d+)/$', views.viyanipon_admin, name='viyanipon_admin'),
    url(r'^search_student/admin_look_school_record/(\d+)/$', views.admin_look_school_record, name='admin_look_school_record'),


    url(r'^admin_look_school_record/$', views.admin_look_school_record, name='admin_look_school_record'),
    url(r'^registeration/$', views.registeration, name='registeration'),
    url(r'^regisResult/$', views.regis_result, name='regis_result'),
    url(r'^schoolRecord/$', views.school_record, name='school_record'),
    url(r'^school_record_admin/(\d+)/$', views.school_record_admin, name='school_record_admin'),
    url(r'^school_record_admin/$', views.school_record_admin_edit, name='school_record_admin_edit'),
    url(r'^search_course/$', views.search_course, name='search_course'),
    url(r'^Find_course/$', views.Find_course, name='Find_course'),
    url(r'^Find_course_admin/$', views.Find_course_admin, name='Find_course_admin'),
    url(r'^Edit_course_admin/$', views.Edit_course_admin, name='Edit_course_admin'),                       

    url(r'^Admin_check_register/$', views.Admin_check_register, name='Admin_check_register'),
    url(r'^Add_course_admin/$', views.Add_course_admin, name='Add_course_admin'),
    url(r'^Admin_drop/$', views.Admin_drop, name='Admin_drop'),
    url(r'^drop/$', views.drop, name='drop'),
    url(r'^drop_admin/$', views.drop_admin, name='drop_admin'),
    url(r'^registeration_admin/$', views.registeration_admin, name='registeration_admin'),
    url(r'^find_registeration_admin/$', views.find_registeration_admin, name='find_registeration_admin'),                  
    url(r'^Find_Admin_check_register/$', views.Find_Admin_check_register, name='Find_Admin_check_register'),
    url(r'^Update_check_admin/$', views.Update_check_admin, name='Update_check_admin'),
    url(r'^Admin_check_drop/$', views.Admin_check_drop, name='Admin_check_drop'),
    url(r'^Find_Admin_check_drop/$', views.Find_Admin_check_drop, name='Find_Admin_check_drop'),
    url(r'^Find_course_drop/$', views.Find_course_drop, name='Find_course_drop'),
    url(r'^Update_check_drop/$', views.Update_check_drop, name='Update_check_drop'),
    url(r'^Find_school_record_admin/$', views.Find_school_record_admin, name='Find_school_record_admin'),
    url(r'^Edit_school_record_admin/$', views.Edit_school_record_admin, name='Edit_school_record_admin'),
    url(r'^Add_register/$', views.Add_register, name='Add_register'),  
    url(r'^viyanipon/$', views.viyanipon, name='viyanipon'),
    url(r'^edit_viyanipon/$', views.edit_viyanipon, name='edit_viyanipon'),
    url(r'^Add_edit_viyanipon/$', views.Add_edit_viyanipon, name='Add_edit_viyanipon'),
                  

      


                       
)



group3/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from group3 import views, views_prof, views_hours

urlpatterns = patterns('',
    #-------------------------------------------------------------------------------------------------------------------
    # prof only อยู่ในอาจารย์ผู้สอนทั้งหมด
    url(r'/prof/index/$',           views_prof.prof_index,          name='prof_index'),
    url(r'/prof/add/$',             views_prof.prof_add,            name='prof_add'),
    url(r'/prof/add/out/$',         views_prof.prof_add_out,        name='prof_add_out'),
    url(r'/prof/add/special/$',     views_prof.prof_add_special,    name='prof_add_special'),
    url(r'/prof/view/(\w+)/$',      views_prof.prof_view,           name='prof_view'),
    url(r'/prof/update/(\w+)/$',    views_prof.prof_update,         name='prof_update'),
    url(r'/prof/delete/(\w+)/$',    views_prof.prof_delete,         name='prof_delete'),
    url(r'/prof/index/sort/(\w+)/$',views_prof.prof_index_sort,     name='prof_sort'),
    #-------------------------------------------------------------------------------------------------------------------
    # อยู่ในหน้าแรกของระบบ อาจารย์สองภาษา
    # เพิ่มการสอน(Teach), เพิ่มอาจารย์นอกภาค, เพิ่มอาจารย์พิเศษ, จัดเรียนการแสดงผลในหน้า index
    url(r'/prof2lang/add/$',        views_prof.prof2langAdd,        name='prof2langAdd'),
    url(r'/prof2lang/add/out/$',    views_prof.prof2langAdd_out,    name='prof2langAdd_out'),
    url(r'/prof2lang/add/special/$',views_prof.prof2langAdd_special,name='prof2langAdd_special'),
    url(r'/prof2lang/sort/(\w+)/$', views.prof2lang_index_sort,     name='prof2lang_sort'),
    #-------------------------------------------------------------------------------------------------------------------
    # แก้ไข ภาคเรียน และ ปีการศึกษา
    url(r'/teach/edit/term/(\d+)/$',views.editTerm,                 name='editTerm'),
    url(r'/teach/edit/year/(\d+)/$',views.editYear,                 name='editYear'),
    #-------------------------------------------------------------------------------------------------------------------
    url(r'/shiftProf/(\d+)/$',      views.shiftProf,                name='shiftProf'),
    url(r'/shiftSubject/(\d+)/$',   views.shiftSubject,             name='shiftSubject'),
    url(r'/shiftSection/(\d+)/$',   views.shiftSection,             name='shiftSection'),
    url(r'/updateProf/(\d+)/$',     views.updateProf,               name='updateProf'),
    url(r'/updateSubject/(\d+)/$',  views.updateSubject,            name='updateSubject'),
    url(r'/updateSection/(\d+)/$',  views.updateSection,            name='updateSection'),
    url(r'/prof2lang/$',            views.prof2lang_index,          name='prof2lang_index'),
    url(r'^prof2lang/(\d+)/$',      views.prof2lang_view,           name='prof2lang_view'),
    url(r'^prof2lang/add/(\d+)$',   views.prof2lang_add,            name='prof2lang_add'),
    url(r'^addProf/$',              views.addProf,                  name='addProf'),
    url(r'^addSubject/$',           views.addSubject,               name='addSubject'),
    url(r'^addSection/$',           views.addSection,               name='addSection'),
    url(r'^testpdf/(\d+)/$',        views.genpdf,                   name='genpdf'),
    url(r'^genallpdf/$',            views.genallpdf,                name='genallpdf'),
    # พนักงานรายชั่วโมง ---------------------------------------------------------------------------------------------------
    #url(r'^hourpdf/(\d+)/$', views.hourpdf, name='hourpdf'), #original
    url(r'^hourpdf/(\d+)/(\d+)/(\d+)/$', views.hourpdf, name='hourpdf'), #scan_time
    url(r'^prof2lang/delete/(\d+)$', views.prof2lang_delete, name='prof2lang_delete'),
    url(r'^hourindex/$', views.hour_index, name='hour_index'),
    url(r'^hourindex/searchname/$', views.search_hour_worker, name='worker_name'),
    url(r'^hourindex/searchname/(\d+)/$', views.returnsearch, name='returnsearch'),
    url(r'^hourindex/searchname/(\d+)/(\d+)/(\d+)/$', views.returnsearch, name='returnsearch'), # scan_time
    url(r'^addhourpage/(\d+)/$', views.add_hour_page, name='add_hour_page'),
    url(r'^add_hour_note/(\d+)/$', views.add_hour_note, name='add_hour_note'),
    url(r'^add_hour_date/(\d+)/$', views.add_hour_date, name='add_hour_date'),
    url(r'^add_hour_date2/(\d+)/$', views.add_hour_date2, name='add_hour_date2'),

    #-------Book-------------#
    url(r'^add_work/(\d+)/$', views_hours.add_work, name='add_work'),
    url(r'^choose_work/(\d+)/$', views_hours.choose_work, name='choose_work'),
    #------------------------#
)

group4/urls.py
from django.conf.urls import patterns, include, url
from group4 import views
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'/userPage/$', views.userPage, name="userPage"),
    url(r'/userPage/commitWC/$', views.commitWithdrawCure, name="commitWithdrawCure"),
    url(r'/userPage/commitWS/$', views.commitWithdrawStudy, name="commitWithdrawStudy"),
    url(r'/adminIndexPage/$', views.adminIndexPage, name="adminIndexPage"),
    url(r'/adminPage/commit_data/(\d+)$', views.commit_data, name="commit_data"),
    url(r'/userPage/addpdf/(\w+)$', views.addpdf, name="addpdf"),
    url(r'/userPage/addpdf2/(\w+)$', views.addpdf2, name="addpdf2"),
    url(r'/userPage/add/commitf/$', views.commitf, name="commitf"),
    url(r'/userPage/add/commitm/$', views.commitm, name="commitm"),
    url(r'/userPage/add/commits/$', views.commits, name="commits"),
    url(r'/userPage/add/commitc/$', views.commitc, name="commitc"),
    url(r'/userPage/add/commitac/(\d+)$', views.commitac, name="commitac"),
    url(r'/userPage/add/commitf2/(\d+)$', views.commitf2, name="commitf2"),
    url(r'/userPage/add/commitm2/(\d+)$', views.commitm2, name="commitm2"),
    url(r'/userPage/add/commits2/(\d+)$', views.commits2, name="commits2"),
    url(r'/userPage/add/commitc2/(\d+)$', views.commitc2, name="commitc2"),


    #url(r'/adminShow/$', views.adminShow, name="adminShow"),
)

login/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from login import views, views_profile

urlpatterns = patterns('',
    # index, login, logout, menu and register --------------------------------------------------------------------------
    url(r'^$',                              views.index,                name='index'),
    url(r'^login/$',                        views.user_login,           name='login'),
    url(r'^logout/$',                       views.user_logout,          name='logout'),
    url(r'^menu/$',                         views.menu,                 name='menu'),
    url(r'^register/$',                     views.user_register,        name='register'),
    url(r'^test/$',                         views.testDateField,        name='testDateField'),
    # information user profile -----------------------------------------------------------------------------------------
    url(r'^profile/$',                      views_profile.index,        name='profile_index'),
    # edit user profile ------------------------------------------------------------------------------------------------
    url(r'^profile/edit/thainame/$',        views_profile.editThaiName, name='profile_editThaiName'),
    url(r'^profile/edit/engname/$',         views_profile.editEngName,  name='profile_editEngName'),
    url(r'^profile/edit/username/$',        views_profile.editUsername, name='profile_editUsername'),
    url(r'^profile/edit/email/$',           views_profile.editEmail,    name='profile_editEmail'),
    url(r'^profile/edit/tel/$',             views_profile.editTel,      name='profile_editTel'),
    url(r'^profile/edit/address/$',         views_profile.editAddress,  name='profile_editAddress'),
    url(r'^profile/edit/office/$',          views_profile.editOffice,   name='profile_editOffice'),
    url(r'^profile/edit/account/$',         views_profile.editAccount,  name='profile_editAccount'),
    url(r'^profile/edit/prefixname/$',      views_profile.editPrefixName,name='profile_editPrefixName'),
    # change password of user ------------------------------------------------------------------------------------------
    url(r'^profile/edit/password/$',        views_profile.editPassword, name='profile_editPassword'),
    # information student profile --------------------------------------------------------------------------------------
    url(r'^profile/student/$',              views_profile.student,      name='profile_student'),
    # information teacher profile --------------------------------------------------------------------------------------
    url(r'^profile/teacher/$',              views_profile.teacher,      name='profile_teacher'),
    # edit teacher profile ---------------------------------------------------------------------------------------------
    url(r'^profile/teacher/edit/prefix/$',  views_profile.editPrefix,   name='profile_editPrefix'),
    url(r'^profile/teacher/edit/shortname/$',views_profile.editShortname,name='profile_editShortname'),
    url(r'^profile/teacher/edit/position/$',views_profile.editTeacherPosition, name='profile_editTeacherPosition'),
    # information officer profile --------------------------------------------------------------------------------------
    url(r'^profile/officer/$',              views_profile.officer,      name='profile_officer'),
    # edit officer profile ---------------------------------------------------------------------------------------------
    url(r'^profile/officer/edit/position/$',views_profile.editOfficerPosition, name='profile_editOfficerPosition'),
)

login/forms.py
from login.models import UserProfile
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.forms.utils import flatatt
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.html import format_html, format_html_join
from django.utils.http import urlsafe_base64_encode
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext, ugettext_lazy as _

class UserForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }

    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput,
                                help_text=_("Enter the same password as above, for verification."))
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

templates/login/index.html
{% extends "start_base.html" %}
{% load staticfiles %}
{% block title %}Database ระบบสารสนเทศ{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="row">
            <div class="container">
                <h1><span class="glyphicon glyphicon-user"></span> {{ user.username }}</h1>
                <a class="btn btn-default" href="{% url 'login:menu' %}">Menu</a><br />
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="container-fluid">
                <main id="content" class="ismartuby-masthead" tabindex="-1" role="main">
                    <p class="container">
                    <img src="{% static 'images/ece_logo_edit.gif' %}" height="200px">
                    <p class="lead-brand">e-Office ECE</p>
                    <p class="lead">สำนักงานอิเล็กทรอนิกส์ ภาควิชาวิศวกรรมไฟฟ้าและคอมพิวเตอร์<br/>
                    คณะวิศวกรรมศาสตร์ มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ</p>
                    <a class="btn btn-success btn-lg" href="{% url 'login:register' %}">ลงทะเบียน</a>
                    <p class="lead lead-label">สำหรับนักศึกษา</p>
                </main>
            </div>
        </div>

        <div class="row">
            <div class="container">


            </div>
        </div>
    {% endif %}

{% endblock %}


























templates/login/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
        <script type="text/javascript" src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <title>Log in เข้าสู่ระบบ</title>
    </head>

    <body>
        <nav class="navbar navbar-inverse navbar-static-top" style="background-color:#00B2EE;">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#id_nav1">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'login:index' %}" style="color:white; font-size:25px;">Database Systems</a>
                </div>

                <div class="collapse navbar-collapse" id="id_nav1">

                </div>
            </div>
    </nav>

        <div class="container">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3>Log in <small>เข้าสู่ระบบ</small></h3>
                        </div>
                        <div class="panel-body">
                            {% if not user.is_authenticated %}
                                {% if error %}
                                    <div class="alert alert-warning alert-dismissible" role="alert">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <strong>Warning!</strong>ไม่สามารถเข้าสู่ระบบเนื่องจาก Username หรือรหัสผ่านไม่ถูกต้อง
                                    </div>
                                {% endif %}
                                <form class="form-horizontal" id="login_form" method="post" action="{% url 'login:login' %}">
                                    {% csrf_token %}

                                    <div class="form-group">
                                        <label for="username" class="col-sm-2 control-label">Username</label>
                                        <div class="col-sm-10">
                                            <input type="text" id="username" name="username" class="form-control"
                                                   value="" placeholder="Username"
                                                   required="">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">Password</label>
                                        <div class="col-sm-10">
                                            <input type="password" name="password" value="" class="form-control"
                                                   placeholder="รหัสผ่าน"
                                                   required="">
                                        </div>
                                    </div>

                                    <br>
                                    <input class="btn btn-primary" type="submit" name="submit" value="Log in">

                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>

    </body>
</html>

templates/login/menu.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Menu เมนู{% endblock %}

{% block pageHeader %}<h1>Menu <small>เมนู</small></h1>{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4>ระบบ <small>งานสารบัญ</small></h4>
                </div>
                <div class="panel-body">
                    {% if user.username == "admin" or user.username == "admin_doc" or user.username == "kaka.kunnikung" or user.username == "pimruthai26" %}
<!--
				 Have to modify by id of username in table
-->
					<a href="{% url 'group1:add_category' %}">เพิ่มหมวดของเอกสาร</a><br>
        		    <a href="{% url 'group1:upload_file' %}">อัพโหลดเอกสาร</a><br>
                    <a href="{% url 'group1:search_file' %}">ค้นหาเอกสาร</a><br>
        		    {% if user.username == "admin" or user.username == "admin_doc" %}
					<a href="{% url 'group1:add_people' %}">ผู้ดูแลเอกสาร</a>
                    {% endif %}
                    {% else %}
                    <a href="{% url 'group1:search_file' %}">ค้นหาเอกสาร</a><br>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4>ระบบ <small>นักศึกษาปริญญาโท, ปริญญาเอก</small></h4>
                </div>
                <div class="panel-body">
                    <a href="{% url 'group2:profile' %}">ประวัตินักศึกษา</a><br>
                    <a href="{% url 'group2:registeration' %}">ลงทะเบียน</a><br>
					<a href="{% url 'group2:school_record' %}">ผลการเรียน</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4>ระบบ <small>งานสอน</small></h4>
                </div>
                <div class="panel-body">
                    <a href="{% url 'group3:prof2lang_index' %}">อาจารย์สองภาษา</a><br>
                    <a href="{% url 'group3:hour_index' %}">พนักงานรายชั่วโมง</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4>ระบบ <small>การเบิกจ่ายค่ารักษาพยาบาล</small></h4>
                </div>
                <div class="panel-body">
                    <a href="{% url 'group4:adminIndexPage' %}">หน้าหลักของผู้ดูแลระบบ</a><br>
                    <a href="{% url 'group4:userPage' %}">หน้าหลักของผู้ใช้งาน</a><br>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4>ระบบ <small>การฝึกงาน</small></h4>
                </div>
                <div class="panel-body">
                    <a href="{% url 'group5:addpet' %}">แบบคำร้องขอหนังสือขอความอนุเคราะห์ฝึกงาน</a><br>
                    <a href="{% url 'group5:status' %}">ตรวจสอบสถานะการฝึกงาน</a><br>
                    <a href="{% url 'group5:company' %}">รายชื่อบริษัทฝึกงาน</a><br>
                    <a href="{% url 'group5:mainG5' %}">รายชื่อนักศึกษาทั้งหมด</a><br>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4>ระบบ <small>จัดการโครงงาน สำหรับนักศึกษา ปริญญาตรี</small></h4>
                </div>
                <div class="panel-body">
                    <a href="{% url 'group6:project_docs_index' %}">ฟอร์มเสนอโครงงานที่สร้างไว้</a><br>
                    <a href="{% url 'group6:project_docs_create_3forms' %}">สร้างฟอร์มเสนอโครงงานใหม่</a><br/>
                    <a href="{% static 'group6/template_ECE_.docx' %}">ตัวอย่างรูปเล่มโปรเจค</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4>ระบบ <small>เบิกจ่ายค่าวัสดุในการทำโครงงาน</small></h4>
                </div>
                <div class="panel-body">
                    <a href="{% url 'group7:index' %}">รายละเอียดแต่ละโครงงาน</a><br>
                    <a href="{% url 'group7:summary' %}">สรุปรายละเอียดการเบิกจ่ายแต่ละโครงงาน</a><br>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/login/test_date_field.html
{% extends "start_base.html" %}
{% load staticfiles %}

{% block title %}ทดสอบ Date Field{% endblock %}

{% block content %}
<div class="row">
    <div class="container">
        <div class="page-header">
            <h2>ทดสอบ <small>Date Field</small></h2>
        </div>

        <form class="form-horizontal" method="post" action="{% url 'login:testDateField' %}">
            {% csrf_token %}

            <script>
                $(function(){
                    $( "#date" ).datepicker({
                        changeMonth: true,
                        changeYear: true,
                        dateFormat: 'dd-mm-yy', // รูปแบบการแสดงผล วัน-เดือน-ปี
                        yearRange: '-100:+0',   // ย้อนหลังไป 100 ปี
                    });
                });
            </script>

            <div class="form-group">
                <label class="col-sm-3 control-label">เลือกวัน</label>
                <div class="col-sm-9">
                    <input type="text" name="date" id="date">
                </div>
            </div>

            <!-- save button -->
            <div class="form-group">
                <label class="col-sm-3 control-label"></label>
                <div class="col-sm-9">
                    <input type="submit" class="btn btn-success" value="ตกลง"/>
                </div>
            </div>

        </form>

    </div>
</div>
{% endblock %}




















