DB_Project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from login import views
from group1 import views
admin.autodiscover()
import os
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DB_Project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('login.urls', namespace="login")),
    url(r'^group1', include('group1.urls', namespace="group1")),
    url(r'^group2', include('group2.urls', namespace="group2")),
    url(r'^group3', include('group3.urls', namespace="group3")),
    url(r'^group4', include('group4.urls', namespace="group4")),
    url(r'^group5', include('group5.urls', namespace="group5")),
    url(r'^group6', include('group6.urls', namespace="group6")),
    url(r'^group7', include('group7.urls', namespace="group7")),
    url(r'^site_media/(?P<path>.*)$',
       'django.views.static.serve',
      {'document_root' : BASE_DIR + '/media'})
)

group6/urls.py
from django.conf.urls import patterns, include, url
from group6 import views

urlpatterns = patterns('',
    url(r'^Project_Docs/$', views.index, name='project_docs_index'), #url of group6 app index page
    url(r'^Project_Docs/create_3forms/$', views.create_3forms, name='project_docs_create_3forms'), #url of create project forms page
    url(r'^Project_Docs/create_3forms/add$', views.create_3forms_add, name='project_docs_create_3forms_add'), #url for save data from project_docs_create_3forms to database
    url(r'^Project_Docs/view_approveProject/(\d+)/$', views.approveProject, name='project_docs_approveProject'), #url to view approveProject forms by project id
    url(r'^Project_Docs/view_offerProject/(\d+)/$', views.offerProject, name='project_docs_offerProject'), #url to view offerProject forms by project id
    url(r'^Project_Docs/view_researchProject/(\d+)/$', views.researchProject, name='project_docs_researchProject'), #url to view researchProject forms by project id
    url(r'^Project_Docs/view_timeLineProject/(\d+)/$', views.timeLineProject, name='project_docs_timeLineProject'), #url to view timeLineProject forms by project id
    url(r'^Project_Docs/view_approveProject/(\d+)/print/$', views.approveProjectPrint, name='project_docs_approveProject_print'), #url to print approveProject forms by project id
    url(r'^Project_Docs/view_offerProject/(\d+)/print/$', views.offerProjectPrint, name='project_docs_offerProject_print'), #url to view print offerProject forms by project id
    url(r'^Project_Docs/view_researchProject/(\d+)/print/$', views.researchProjectPrint, name='project_docs_researchProject_print'), #url to view print researchProject forms by project id
    url(r'^Project_Docs/view_timeLineProject/(\d+)/print/$', views.timeLineProjectPrint, name='project_docs_timeLineProject_print'), #url to view print timeLineProject forms by project id (black tab)
    url(r'^Project_Docs/view_timeLineProject/(\d+)/print_check/$', views.timeLineProjectPrintCheck, name='project_docs_timeLineProject_print_check'), #url to print timeLineProject forms by project id (checkbox)
    url(r'^Project_Docs/delete/(\d+)/$', views.deleteForm, name='project_docs_delete'), #url for delete project and all data of this project
    url(r'^Project_Docs/edit/(\d+)/$', views.edit_3forms, name='project_docs_edit'), #url for render edit project forms page by project id
    url(r'^Project_Docs/edit/(\d+)/update$', views.edit_3forms_update, name='project_docs_edit_update'), #url to update project forms data in database from project_docs_edit by project id
    url(r'^Project_Docs/add_categories_tester/(\d+)/$', views.add_categories_tester, name='project_docs_add_categories_tester'), #url for render page to set categories project number and tester
    url(r'^Project_Docs/add_categories_tester/(\d+)/add$', views.add_categories_tester_add, name='project_docs_add_categories_tester_add'), #url for save data from project_docs_add_categories_tester to database
    url(r'^Project_Docs/edit_categories_tester/(\d+)/$', views.edit_categories_tester, name='project_docs_edit_categories_tester'), #url for render edit categories project number and tester page by CategoriesProject id
    url(r'^Project_Docs/edit_categories_tester/(\d+)/update$', views.edit_categories_tester_update, name='project_docs_edit_categories_tester_update'), #url to update categories project number and tester data in database from project_docs_edit_categories_tester by CategoriesProject id
    url(r'^Project_Docs/add_notification/(\d+)/$', views.add_notification, name='project_docs_add_notification'), #url for render page to create new notification page
    url(r'^Project_Docs/add_notification/(\d+)/add$', views.add_notification_add, name='project_docs_add_notification_add'), #url for save data from project_docs_add_notification to database
    url(r'^Project_Docs/view_notification/(\d+)/$', views.view_notification, name='project_docs_view_notification'), #url for render page to view notification by notification id
    url(r'^Project_Docs/view_notification/(\d+)/reply_message/$', views.reply_message, name='project_docs_reply_message'), #url for render page to reply message on notification page
    url(r'^Project_Docs/view_notification/(\d+)/reply_message/add$', views.reply_message_add, name='project_docs_reply_message_add'), #url for save data from project_docs_reply_message to database
    url(r'^Project_Docs/view_notification/(?P<nID>\d+)/edit_message/(?P<mID>\d+)/$', views.edit_notification_message, name='project_docs_edit_notification_message'), #url for render page to edit message by message id
    url(r'^Project_Docs/view_notification/(?P<nID>\d+)/edit_message/(?P<mID>\d+)/update$', views.edit_notification_message_update, name='project_docs_edit_notification_message_update'), #url to update message data in database from project_docs_edit_notification_message by message id
    url(r'^Project_Docs/view_notification/(\d+)/delete$', views.delete_notification, name='project_docs_delete_notification'), #url for delete notification and all message of notification by notification id
)

login/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from login import views, views_profile

urlpatterns = patterns('',
    # index, login, logout, menu and register --------------------------------------------------------------------------
    url(r'^$',                              views.index,                name='index'),
    url(r'^login/$',                        views.user_login,           name='login'),
    url(r'^logout/$',                       views.user_logout,          name='logout'),
    url(r'^menu/$',                         views.menu,                 name='menu'),
    url(r'^register/$',                     views.user_register,        name='register'),
    url(r'^test/$',                         views.testDateField,        name='testDateField'),
    # information user profile -----------------------------------------------------------------------------------------
    url(r'^profile/$',                      views_profile.index,        name='profile_index'),
    # edit user profile ------------------------------------------------------------------------------------------------
    url(r'^profile/edit/thainame/$',        views_profile.editThaiName, name='profile_editThaiName'),
    url(r'^profile/edit/engname/$',         views_profile.editEngName,  name='profile_editEngName'),
    url(r'^profile/edit/username/$',        views_profile.editUsername, name='profile_editUsername'),
    url(r'^profile/edit/email/$',           views_profile.editEmail,    name='profile_editEmail'),
    url(r'^profile/edit/tel/$',             views_profile.editTel,      name='profile_editTel'),
    url(r'^profile/edit/address/$',         views_profile.editAddress,  name='profile_editAddress'),
    url(r'^profile/edit/office/$',          views_profile.editOffice,   name='profile_editOffice'),
    url(r'^profile/edit/account/$',         views_profile.editAccount,  name='profile_editAccount'),
    url(r'^profile/edit/prefixname/$',      views_profile.editPrefixName,name='profile_editPrefixName'),
    # change password of user ------------------------------------------------------------------------------------------
    url(r'^profile/edit/password/$',        views_profile.editPassword, name='profile_editPassword'),
    # information student profile --------------------------------------------------------------------------------------
    url(r'^profile/student/$',              views_profile.student,      name='profile_student'),
    # information teacher profile --------------------------------------------------------------------------------------
    url(r'^profile/teacher/$',              views_profile.teacher,      name='profile_teacher'),
    # edit teacher profile ---------------------------------------------------------------------------------------------
    url(r'^profile/teacher/edit/prefix/$',  views_profile.editPrefix,   name='profile_editPrefix'),
    url(r'^profile/teacher/edit/shortname/$',views_profile.editShortname,name='profile_editShortname'),
    url(r'^profile/teacher/edit/position/$',views_profile.editTeacherPosition, name='profile_editTeacherPosition'),
    # information officer profile --------------------------------------------------------------------------------------
    url(r'^profile/officer/$',              views_profile.officer,      name='profile_officer'),
    # edit officer profile ---------------------------------------------------------------------------------------------
    url(r'^profile/officer/edit/position/$',views_profile.editOfficerPosition, name='profile_editOfficerPosition'),
)

group6/models.py
from django.db import models
from login.models import *

#model to store project data
class ProjectG6(models.Model):
    student = models.ManyToManyField(Student) #link to Student many to many
    teacher = models.ForeignKey(Teacher) #link to Teacher entity one to one
    name_thai = models.CharField(max_length=200) #name of project thai languages
    name_eng = models.CharField(max_length=200) #name of project english languages
    yearOfEducation = models.IntegerField(default = 1) #year of education for project
    objective = models.TextField() #objective of project
    reason = models.TextField() #reason of project
    scope = models.TextField() #scope of project
    benefit = models.TextField() #benefit of project

    def __unicode__(self): #pattern of data to show in admin page
        return self.name_eng

class CategoriesProject(models.Model):
    project = models.ForeignKey(ProjectG6) #Link to Project entity one to one
    project_catagories = models.CharField(max_length=5) #categories of project
    number = models.CharField(max_length=2) #number of project
    year = models.CharField(max_length=2) #year of education project
    semester = models.IntegerField(default=1) #semester of project
    teacher = models.ManyToManyField(Teacher) #link to Teacher many to many (Teacher that tester for this project)

    def __unicode__(self): #pattern of data to show in admin page
        return self.project.name_eng

class ResearchProjectForm(models.Model):
    project = models.ForeignKey(ProjectG6) #Link to Project entity one to one
    numberOfPeople = models.IntegerField(default = 1) #number of student in project

    def __unicode__(self): #pattern of data to show in admin page
        return self.project.name_eng

class OfferProjectForm(models.Model):
    project = models.ForeignKey(ProjectG6) #Link to Project entity one to one
    priceOfMaterial = models.FloatField(default=0.00) #price of material in project
    priceOfOther = models.FloatField(default=0.00) #price of other in project

    def __unicode__(self): #pattern of data to show in admin page
        return self.project.name_eng

class ApproveProjectForm(models.Model):
    project = models.ForeignKey(ProjectG6) #Link to Project entity one to one
    student = models.ForeignKey(Student) #link to Student one to one
    course = models.CharField(max_length=200) #course of this project
    semesterEnd = models.CharField(max_length=200) #semester to end this project
    yearEnd = models.CharField(max_length=200) #year of education to end this project
    credit = models.IntegerField(default = 3) #credit of course

    def __unicode__(self): #pattern of data to show in admin page
        return self.project.name_eng

class TimeLineForm(models.Model):
    project = models.ForeignKey(ProjectG6) #Link to Project entity one to one
    day = models.IntegerField(default = 1) #start project day
    month = models.CharField(max_length=200) #start project month
    year= models.IntegerField(default = 1) #start project year
    note = models.TextField() #forms note

    def __unicode__(self): #pattern of data to show in admin page
        return self.project.name_eng

class StepInTimeLine(models.Model):
    timeline = models.ForeignKey(TimeLineForm) #Link to TimeLineForm entity Many to one
    numberOfProcess = models.IntegerField(default = 1) #number of process in forms timeline
    processDescription = models.CharField(max_length=200) #process description
    month1 = models.BooleanField(default=False) #month1 check box
    month2 = models.BooleanField(default=False) #month2 check box
    month3 = models.BooleanField(default=False) #month3 check box
    month4 = models.BooleanField(default=False) #month4 check box
    month5 = models.BooleanField(default=False) #month5 check box
    month6 = models.BooleanField(default=False) #month6 check box
    month7 = models.BooleanField(default=False) #month7 check box
    month8 = models.BooleanField(default=False) #month8 check box
    month9 = models.BooleanField(default=False) #month9 check box
    month10 = models.BooleanField(default=False) #month10 check box
    month11 = models.BooleanField(default=False) #month11 check box
    month12 = models.BooleanField(default=False) #month12 check box

    def __unicode__(self): #pattern of data to show in admin page
        return self.timeline.project.name_eng + " (" + self.processDescription + ")"

class NotificationProject(models.Model):
    project = models.ForeignKey(ProjectG6) #Link to Project entity Many to one
    officer = models.ForeignKey(Officer) #link to Officer entity one to one (Officer that create notification)

    def __unicode__(self): #pattern of data to show in admin page
        return self.project.name_eng

class Message(models.Model):
    text = models.TextField() #message field
    user = models.ForeignKey(UserProfile) #user create message
    noti = models.ForeignKey(NotificationProject) #Link to NotificationProject entity Many to one
    pub_date = models.DateTimeField('date published') #first time create message
    pub_date_last = models.DateTimeField('last edit') #last time to edit message

    def __unicode__(self): #pattern of data to show in admin page
        return self.noti.project.name_eng + " (" + self.pub_date + ")"

templates/group6/index.html
<!-- Extend in base.html as a body -->
{% extends "base.html" %}
<!-- Use customfunction in this page -->
{% load custom_function %}
<!-- Use staticfiles in this page -->
{% load staticfiles %}
<!-- Command for setting title of page -->
{% block title %}ระบบ จัดการโครงงาน สำหรับนักศึกษา ปริญญาตรี{% endblock %}
<!-- Command for setting header of page -->
{% block pageHeader %}
<h2>ระบบ <small>จัดการโครงงาน สำหรับนักศึกษา ปริญญาตรี</small></h2>
<ol class="breadcrumb">
    <li><a href="{% url 'login:menu' %}">เมนู</a></li>
    <li class="active">ระบบ จัดการโครงงาน สำหรับนักศึกษา ปริญญาตรี</li>
</ol>
{% endblock %}
<!-- This for content in base.html -->
{% block content %}

<!-- after this are HTML coding  -->
<!-- {.{ ... }} is syntax for access database and add | for function in custom_function ("{.{" to avoid error) -->
<!-- {.% ... %} is syntax for operation ex. if/else , forloop, etc. ("{.%" to aviod error) -->
<div class="container-fluid">
    {% for message in messages %}
        <br><font color = "FF0000" name="message">*{{ message }}</font>
    {% endfor %}
    {% if project_list %}  
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped" id="no-more-tables">
                    <thead>
                        <tr>
                            <th>ลำดับ</th>
                            <th>รหัสโครงงาน</th>
                            <th>ชื่อโครงงาน (ภาษาไทย)</th>
                            <th>ชื่อโครงงาน (ภาษาอังกฤษ)</th>
                            <th>แบบฟอร์มสำรวจหัวข้อโครงงานปริญญานิพนธ์</th>
                            <th>แบบเสนอโครงงานปริญญานิพนธ์</th>
                            <th>แบบเสนอขออนุมัติโครงงานปริญญานิพนธ์</th>
                            <th>ขั้นตอนการดำเนินงานแนวคิดกับแผนที่วางไว้</th>
                            <th>ข้อความแจ้งเตือน</th>
                            <th>เมนูสำหรับแบบฟอร์ม</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for project in project_list %}
                        <tr>
                            <td data-title="ลำดับ">{{ forloop.counter }}</td>
                            <td data-title="รหัสโครงงาน">{{ project_id|get_at_index:forloop.counter0 }}</td>
                            <td data-title="ชื่อโครงงาน (ภาษาไทย)">{{ project.name_thai }}</td>
                            <td data-title="ชื่อโครงงาน (ภาษาอังกฤษ)">{{ project.name_eng }}</td>
                            <td data-title="แบบฟอร์มสำรวจหัวข้อโครงงานปริญญานิพนธ์"><a class="btn btn-info" href="{% url 'group6:project_docs_researchProject' research|get_id_at_index:forloop.counter0 %}">ดูฟอร์ม</a></td>
                            <td data-title="แบบเสนอโครงงานปริญญานิพนธ์"><a class="btn btn-warning" href="{% url 'group6:project_docs_offerProject' offer|get_id_at_index:forloop.counter0 %}">ดูฟอร์ม</a></td>
                            <td data-title="แบบเสนอขออนุมัติโครงงานปริญญานิพนธ์"><a class="btn btn-success" href="{% url 'group6:project_docs_approveProject' approve|get_id_at_index:forloop.counter0 %}">ดูฟอร์ม</a></td>
                            <td data-title="ขั้นตอนการดำเนินงานแนวคิดกับแผนที่วางไว้"><a class="btn btn-default" href="{% url 'group6:project_docs_timeLineProject' timeLine|get_id_at_index:forloop.counter0 %}">ดูฟอร์ม</a></td>
                            <td data-title="ข้อความแจ้งเตือน">{% for text in message|get_at_index:forloop.counter0 %}
                            <a class="btn btn-link" href="{% url 'group6:project_docs_view_notification' text.id %}">ข้อความแจ้งเตือนที่ {{ forloop.counter }}</a><br>{% endfor %}</td>
                            <td data-title="เมนูสำหรับแบบฟอร์ม">
                                <a class="btn btn-danger" href="javascript:if(confirm('คุณต้องการจะลบฟอร์มนี้ใช่หรือไม่ หากใช่ให้กด OK'))
window.location='{% url 'group6:project_docs_delete' project.id %}';" target="_blank">ลบแบบฟอร์ม</a><br>
                                <a class="btn btn-link" href="{% url 'group6:project_docs_edit' project.id %}">แก้ไขแบบฟอร์ม</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
    {% else %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="alert alert-warning" role="alert">
                    <strong>ยังไม่มีข้อมูล!</strong> กรุณา
                    <a class="alert-link" href="#">เพิ่มข้อมูล</a>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    {% endif %}
    <a class="btn btn-primary" href="{% url 'group6:project_docs_create_3forms' %}">สร้างฟอร์มเสนอโครงงานใหม่</a> 
    <a class="btn btn-info" href="{% static "group6/template_ECE_.docx" %}">ตัวอย่างรูปเล่มโปรเจค</a><br>
</div><br>
{% endblock %}

templates/group6/notification_view.html
<!-- Extend in base.html as a body -->
{% extends "base.html" %}
<!-- Use customfunction in this page -->
{% load custom_function %}
<!-- Command for setting title of page -->
{% block title %}ระบบ จัดการโครงงาน สำหรับนักศึกษา ปริญญาตรี - แจ้งเตือน{% endblock %}
<!-- Command for setting header of page -->
{% block pageHeader %}
<h2>ระบบ <small>จัดการโครงงาน สำหรับนักศึกษา ปริญญาตรี</small></h2>
<ol class="breadcrumb">
    <li><a href="{% url 'login:menu' %}">เมนู</a></li>
    <li><a href="{% url 'group6:project_docs_index' %}">ระบบ จัดการโครงงาน สำหรับนักศึกษา ปริญญาตรี</a></li>
    <li class="active">แจ้งเตือน</li>
</ol>
{% endblock %}
<!-- This for content in base.html -->
{% block content %}
<div class="container-fluid">
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <!-- Style sheet : Use CSS for each tag name or class -->
    <style>
    table,tr,td{
        border-collapse: collapse;
    }
    body{
       background-color:white;
   }
   .page{
       width:210mm;
       margin:auto;
       position:relative;
       padding: 2cm;
       border: 1px #D3D3D3 solid;
       border-radius: 5px;
       background: white;
   }
   .form > H{
       margin-left:10;
   }
   .namestd{
       margin-left:10;
   }
   textarea {
       margin-left:10;
       resize:none;
       outline:none;
   }
   H{
       font:16pt "Angsana New";
   }
   input{
       outline:none;
       resize:none;
   }
   #o1{
       text-align:center;
   }
  </style>
  
<!-- after this are HTML coding  -->
<!-- {.{ ... }} is syntax for access database and add | for function in custom_function ("{.{" to avoid error) -->
<!-- {.% ... %} is syntax for operation ex. if/else , forloop, etc. ("{.%" to aviod error) -->
        <div class="page">
            <label class="form">
            {% for mes in message %}
            <H>{{ mes.text }}</H><br>
                  โดย {% if mes.user.type == '0' %}{{ mes.user.prefix_name|get_prefix_name_th }}{% elif mes.user.type == '2' %}{{ mes.user.prefix_name|get_prefix_name_th }}{% elif mes.user.type == '1' %}{{ mes.user.id|get_prefix_name_th_teacher_message }}{% endif %} {{ mes.user.firstname_th }} {{ mes.user.lastname_th }} เมื่อ {{ mes.pub_date }}<br>แก้ไขล่าสุดเมื่อ {{ mes.pub_date_last }}
            {% if user_now.id == mes.user.id %}<a class="btn btn-info btn-xs" href="{% url 'group6:project_docs_edit_notification_message' notification.id mes.id %}">Edit Message</a>{% endif %}<br><br>
            {% endfor %}
            
            </label>
   </div>
   <center><br>
    <a class="btn btn-primary" href="{% url 'group6:project_docs_reply_message' notification.id %}">ตอบกลับ</a>
    <a href="{% url 'group6:project_docs_index' %}"><input class="btn btn-danger" type="button" value="ย้อนกลับ" name = 'cancel' /></a>
    {% if user_now.id == notification.officer.userprofile.id %}
    <a class="btn btn-danger" href="javascript:if(confirm('คุณต้องการจะลบการแจ้งเตือนนี้ใช่หรือไม่ หากใช่ให้กด OK'))
window.location='{% url 'group6:project_docs_delete_notification' notification.id %}';" target="_blank">ลบแบบฟอร์ม</a>
    {% endif %}
</center>
<br>
</div>
{% endblock %}

templates/group6/researchProject_view.html
<!-- Extend in base.html as a body -->
{% extends "base.html" %}
<!-- Use customfunction in this page -->
{% load custom_function %}
<!-- Command for setting title of page -->
{% block title %}ระบบ จัดการโครงงาน สำหรับนักศึกษา ปริญญาตรี - แบบฟอร์มสำรวจหัวข้อโครงงานปริญญานิพนธ์ - {{ research.project.name_thai }}{% endblock %}
<!-- Command for setting header of page -->
{% block pageHeader %}
<h2>ระบบ <small>จัดการโครงงาน สำหรับนักศึกษา ปริญญาตรี</small></h2>
<ol class="breadcrumb">
    <li><a href="{% url 'login:menu' %}">เมนู</a></li>
    <li><a href="{% url 'group6:project_docs_index' %}">ระบบ จัดการโครงงาน สำหรับนักศึกษา ปริญญาตรี</a></li>
    <li class="active">แบบฟอร์มสำรวจหัวข้อโครงงานปริญญานิพนธ์ - {{ research.project.name_thai }}</li>
</ol>
{% endblock %}
<!-- This for content in base.html -->
{% block content %}
<div class="container-fluid">
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<!-- Style sheet : Use CSS for each tag name or class -->
<style>
body{
	}
*{
	word-wrap:normal;
	word-break:break-all;
}
.page{
	font:14pt "Angsana New";
	width:170mm;
	height:auto;
	margin:auto;
	position:relative;
    padding: 2cm;
    border:solid;
	border-width:thin;
    background: white;
	}
.form > H{
	margin-left:0;
}
.text{
	border:none; /*Use for change border width*/
	resize:none;
	margin-left:0;
	float:none;
	
	}
#nameeng{
	padding-left:18mm;
	}
#yearspace{
	display:block;
	margin-bottom:10mm;
	 }
#nameth{
	padding-left:2mm;
	}
@media print {
	.page {
		font:14pt "Angsana New";
		margin-top:21mm;
		margin-left:26mm;
		margin-right:14mm;
		padding:0;
		width:initial;
		height:initial;
		size:portrait;
		position:static;
		border:0;
		border-radius:0;
		box-shadow: initial;
		background: initial;
		page-break-after: auto;
		display:block;
		}
	#nameeng{
		padding-left:18mm;
		}
	.text{
		margin-left:0;
	}
	#yearspace{
		display:block;
		margin-bottom:10mm;
		 }
	#nameth{
		padding-left:2mm;
		}
}
</style>
<!-- after this are HTML coding  -->
<!-- {.{ ... }} is syntax for access database and add | for function in custom_function ("{.{" to avoid error) -->
<!-- {.% ... %} is syntax for operation ex. if/else , forloop, etc. ("{.%" to aviod error) -->
<div class="page">
<center>
<H><b>แบบฟอร์มสำรวจหัวข้อโครงงานปริญญานิพนธ์</b></H><br>
<H>ภาควิชาวิศวกรรมไฟฟ้าและคอมพิวเตอร์ คณะวิศวกรรมศาสตร์</H><br>
<H>มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ</H><br>
<br id="yearspace">
<H>ปีการศึกษา {{ research.project.yearOfEducation }}</H><br>
<br id="yearspace">
</center>
<label class="form">
<H>ชื่อโครงการ</H><H id="nameth">(ภาษาไทย)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ research.project.name_thai }}</H><br>
<H id="nameeng">(ภาษาอังกฤษ)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ research.project.name_eng }}</H><br>
<H>จำนวนนักศึกษา {{ research.numberOfPeople }} คน </H><br>
<H>ชื่ออาจารย์ที่ปรึกษา&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ research.project.teacher.academic_position|get_prefix_name_th_teacher:research.project.teacher.userprofile.prefix_name }} {{ research.project.teacher.userprofile.firstname_th }} {{ research.project.teacher.userprofile.lastname_th }} ({{ research.project.teacher.shortname }})</H>
	<div class="text">วัตถุประสงค์&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ research.project.objective }}</div>
	<div class="text">แนวเหตุผล ทฤษฎีสำคัญหรือสมมติฐาน&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ research.project.reason }}</div>
	<div class="text">ขอบเขตของการทำโครงการ&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ research.project.scope }}</div>
	<div class="text">ผลประโยชน์ที่คาดว่าจะได้รับ&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ research.project.benefit }}</div>
	</label>
</div>
<br>
<a href="{% url 'group6:project_docs_index' %}"><input class="btn btn-danger" type="button" value="ย้อนกลับ" name = 'cancel' /></a> 
<a class="btn btn-default" href="javascript:if(confirm('! คำเตือน !\n
ใช้ Browser : Chrome\n
ขนาดกระดาษ : A4\n
ระยะขอบ : ไม่มี\n
รูปแบบ : แนวตั้ง\n\n
! Warning !\n
Use browser : Chrome\n
Size : A4\n
Margin : None\n
Style : Portrait'))
window.open('{% url 'group6:project_docs_researchProject_print' research.id %}', '_blank');"><span class="glyphicon glyphicon-print"></span></a>
</div><br>
{% endblock %}