DB_Project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from login import views
from group1 import views
admin.autodiscover()
import os
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DB_Project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('login.urls', namespace="login")),
    url(r'^group1', include('group1.urls', namespace="group1")),
    url(r'^group2', include('group2.urls', namespace="group2")),
    url(r'^group3', include('group3.urls', namespace="group3")),
    url(r'^group4', include('group4.urls', namespace="group4")),
    url(r'^group5', include('group5.urls', namespace="group5")),
    url(r'^group6', include('group6.urls', namespace="group6")),
    url(r'^group7', include('group7.urls', namespace="group7")),
    url(r'^site_media/(?P<path>.*)$',
       'django.views.static.serve',
      {'document_root' : BASE_DIR + '/media'})
)

group3/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from group3 import views, views_prof, views_hours

urlpatterns = patterns('',
    #-------------------------------------------------------------------------------------------------------------------
    # prof only อยู่ในอาจารย์ผู้สอนทั้งหมด
    url(r'/prof/index/$',           views_prof.prof_index,          name='prof_index'),
    url(r'/prof/add/$',             views_prof.prof_add,            name='prof_add'),
    url(r'/prof/add/out/$',         views_prof.prof_add_out,        name='prof_add_out'),
    url(r'/prof/add/special/$',     views_prof.prof_add_special,    name='prof_add_special'),
    url(r'/prof/view/(\w+)/$',      views_prof.prof_view,           name='prof_view'),
    url(r'/prof/update/(\w+)/$',    views_prof.prof_update,         name='prof_update'),
    url(r'/prof/delete/(\w+)/$',    views_prof.prof_delete,         name='prof_delete'),
    url(r'/prof/index/sort/(\w+)/$',views_prof.prof_index_sort,     name='prof_sort'),
    #-------------------------------------------------------------------------------------------------------------------
    # อยู่ในหน้าแรกของระบบ อาจารย์สองภาษา
    # เพิ่มการสอน(Teach), เพิ่มอาจารย์นอกภาค, เพิ่มอาจารย์พิเศษ, จัดเรียนการแสดงผลในหน้า index
    url(r'/prof2lang/add/$',        views_prof.prof2langAdd,        name='prof2langAdd'),
    url(r'/prof2lang/add/out/$',    views_prof.prof2langAdd_out,    name='prof2langAdd_out'),
    url(r'/prof2lang/add/special/$',views_prof.prof2langAdd_special,name='prof2langAdd_special'),
    url(r'/prof2lang/sort/(\w+)/$', views.prof2lang_index_sort,     name='prof2lang_sort'),
    #-------------------------------------------------------------------------------------------------------------------
    # แก้ไข ภาคเรียน และ ปีการศึกษา
    url(r'/teach/edit/term/(\d+)/$',views.editTerm,                 name='editTerm'),
    url(r'/teach/edit/year/(\d+)/$',views.editYear,                 name='editYear'),
    #-------------------------------------------------------------------------------------------------------------------
    url(r'/shiftProf/(\d+)/$',      views.shiftProf,                name='shiftProf'),
    url(r'/shiftSubject/(\d+)/$',   views.shiftSubject,             name='shiftSubject'),
    url(r'/shiftSection/(\d+)/$',   views.shiftSection,             name='shiftSection'),
    url(r'/updateProf/(\d+)/$',     views.updateProf,               name='updateProf'),
    url(r'/updateSubject/(\d+)/$',  views.updateSubject,            name='updateSubject'),
    url(r'/updateSection/(\d+)/$',  views.updateSection,            name='updateSection'),
    url(r'/prof2lang/$',            views.prof2lang_index,          name='prof2lang_index'),
    url(r'^prof2lang/(\d+)/$',      views.prof2lang_view,           name='prof2lang_view'),
    url(r'^prof2lang/add/(\d+)$',   views.prof2lang_add,            name='prof2lang_add'),
    url(r'^addProf/$',              views.addProf,                  name='addProf'),
    url(r'^addSubject/$',           views.addSubject,               name='addSubject'),
    url(r'^addSection/$',           views.addSection,               name='addSection'),
    url(r'^testpdf/(\d+)/$',        views.genpdf,                   name='genpdf'),
    url(r'^genallpdf/$',            views.genallpdf,                name='genallpdf'),
    # พนักงานรายชั่วโมง ---------------------------------------------------------------------------------------------------
    #url(r'^hourpdf/(\d+)/$', views.hourpdf, name='hourpdf'), #original
    url(r'^hourpdf/(\d+)/(\d+)/(\d+)/$', views.hourpdf, name='hourpdf'), #scan_time
    url(r'^prof2lang/delete/(\d+)$', views.prof2lang_delete, name='prof2lang_delete'),
    url(r'^hourindex/$', views.hour_index, name='hour_index'),
    url(r'^hourindex/searchname/$', views.search_hour_worker, name='worker_name'),
    url(r'^hourindex/searchname/(\d+)/$', views.returnsearch, name='returnsearch'),
    url(r'^hourindex/searchname/(\d+)/(\d+)/(\d+)/$', views.returnsearch, name='returnsearch'), # scan_time
    url(r'^addhourpage/(\d+)/$', views.add_hour_page, name='add_hour_page'),
    url(r'^add_hour_note/(\d+)/$', views.add_hour_note, name='add_hour_note'),
    url(r'^add_hour_date/(\d+)/$', views.add_hour_date, name='add_hour_date'),
    url(r'^add_hour_date2/(\d+)/$', views.add_hour_date2, name='add_hour_date2'),

    #-------Book-------------#
    url(r'^add_work/(\d+)/$', views_hours.add_work, name='add_work'),
    url(r'^choose_work/(\d+)/$', views_hours.choose_work, name='choose_work'),
    #------------------------#
)

login/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from login import views, views_profile

urlpatterns = patterns('',
    # index, login, logout, menu and register --------------------------------------------------------------------------
    url(r'^$',                              views.index,                name='index'),
    url(r'^login/$',                        views.user_login,           name='login'),
    url(r'^logout/$',                       views.user_logout,          name='logout'),
    url(r'^menu/$',                         views.menu,                 name='menu'),
    url(r'^register/$',                     views.user_register,        name='register'),
    url(r'^test/$',                         views.testDateField,        name='testDateField'),
    # information user profile -----------------------------------------------------------------------------------------
    url(r'^profile/$',                      views_profile.index,        name='profile_index'),
    # edit user profile ------------------------------------------------------------------------------------------------
    url(r'^profile/edit/thainame/$',        views_profile.editThaiName, name='profile_editThaiName'),
    url(r'^profile/edit/engname/$',         views_profile.editEngName,  name='profile_editEngName'),
    url(r'^profile/edit/username/$',        views_profile.editUsername, name='profile_editUsername'),
    url(r'^profile/edit/email/$',           views_profile.editEmail,    name='profile_editEmail'),
    url(r'^profile/edit/tel/$',             views_profile.editTel,      name='profile_editTel'),
    url(r'^profile/edit/address/$',         views_profile.editAddress,  name='profile_editAddress'),
    url(r'^profile/edit/office/$',          views_profile.editOffice,   name='profile_editOffice'),
    url(r'^profile/edit/account/$',         views_profile.editAccount,  name='profile_editAccount'),
    url(r'^profile/edit/prefixname/$',      views_profile.editPrefixName,name='profile_editPrefixName'),
    # change password of user ------------------------------------------------------------------------------------------
    url(r'^profile/edit/password/$',        views_profile.editPassword, name='profile_editPassword'),
    # information student profile --------------------------------------------------------------------------------------
    url(r'^profile/student/$',              views_profile.student,      name='profile_student'),
    # information teacher profile --------------------------------------------------------------------------------------
    url(r'^profile/teacher/$',              views_profile.teacher,      name='profile_teacher'),
    # edit teacher profile ---------------------------------------------------------------------------------------------
    url(r'^profile/teacher/edit/prefix/$',  views_profile.editPrefix,   name='profile_editPrefix'),
    url(r'^profile/teacher/edit/shortname/$',views_profile.editShortname,name='profile_editShortname'),
    url(r'^profile/teacher/edit/position/$',views_profile.editTeacherPosition, name='profile_editTeacherPosition'),
    # information officer profile --------------------------------------------------------------------------------------
    url(r'^profile/officer/$',              views_profile.officer,      name='profile_officer'),
    # edit officer profile ---------------------------------------------------------------------------------------------
    url(r'^profile/officer/edit/position/$',views_profile.editOfficerPosition, name='profile_editOfficerPosition'),
)

group3/models.py
#-*- coding: utf-8 -*-
from django.db import models
from login.models import *
import datetime, time
# Create your models here.
class Prof2Lang(models.Model):
    # the professor ID is primary key
    profID = models.CharField(primary_key=True, max_length=10)                      # 1. * profID
    # professor profile
    firstName = models.CharField(max_length=50)                                     # 2. * firstName
    lastName = models.CharField(max_length=80)                                      # 3. * lastName
    shortName = models.CharField(max_length=3)                                      # 4. * shortName

    tell = models.CharField(blank=True, max_length=15)                              # 5. tell
    email = models.EmailField(blank=True)                                           # 6. email
    sahakornAccount = models.CharField(blank=True, max_length=100, default=True)    # 7. sahakornAccount

    department = models.CharField(max_length=200, blank=True, default="")           # 8. department
    faculty = models.CharField(max_length=200, blank=True, default="")              # 9. faculty

    typeChoices = (
        ('0','อาจารย์ในภาควิชา'),
        ('1','อาจารย์นอกภาควิชา'),
        ('2','อาจารย์พิเศษ')
    )
    type = models.CharField(max_length=1, choices=typeChoices)                      # 10. * type ประเภทอาจารย์

    prefix_name_choices = (
        ('0', 'นาย'),       # Mr.
        ('1', 'นาง'),       # Mrs.
        ('2', 'นางสาว'),    # Miss.
        ('3', 'ดร.'),       # Dr.
        ('4', 'อาจารย์')     # อ.
    )
    prefix_name  = models.CharField(max_length=1, choices=prefix_name_choices)      # 11. * คำนำหน้าชื่อ

    academic_position_choice = (
        ('0', ''),
        ('1', 'ผู้ช่วยศาสตราจารย์'),    # ตัวย่อไทย ผศ.  ตัวย่อแบบอเมริกา  Asst.Prof.   มาจาก Assistant Professor
        ('2', 'รองศาสตราจารย์'),     # ตัวย่อไทย รศ.  ตัวย่อแบบอเมริกา  Assoc.Prof.  มาจาก Associate Professor
        ('3', 'ศาสตราจารย์')          # ตัวย่อไทย ศ.   ตัวย่อแบบอเมริกา Prof.         มาจาก Professor
    )
    academic_position = models.CharField(max_length=1, choices=academic_position_choice)    # 12. ตำแหน่งทางวิชาการ

    def __unicode__(self):
        return self.firstName + " " + self.lastName

class Subject(models.Model):
    subjectID = models.CharField(primary_key=True, max_length=9)                # 1. รหัสวิชา
    subjectName = models.CharField(max_length=200)                              # 2. ชื่อวิชาภาษาอังกฤษ
    subjectName_th = models.CharField(max_length=200, default='')               # 3. ชื่อวิชาภาษาไทย

    def __unicode__(self):
        return self.subjectName

class Section(models.Model):
    section = models.CharField(max_length=7)                                    # 1. ชื่อ section เช่น S.1
    subject = models.ForeignKey(Subject)                                        # 2. วิชา (subject)
    classroom = models.CharField(max_length=20)                                 # 3. ห้องเรียน
    startTime = models.TimeField()                                              # 4. เวลาเริ่มเรียน
    endTime = models.TimeField()                                                # 5. เวลาเลิกเรียน

    dateChoices = (
        ('M', 'Monday'),
        ('T', 'Tuesday'),
        ('W', 'Wednesday'),
        ('H', 'Thursday'),
        ('F', 'Friday'),
        ('S', 'Saturday')
    )
    date = models.CharField(max_length=1, choices=dateChoices)                  # 6. วันที่เรียน เช่น จันทร์

    def __unicode__(self):
        return self.section + " " + self.subject.subjectName

    class meta:
        unique_together = ('section', 'subject')

class Teach(models.Model):
    prof = models.ForeignKey(Prof2Lang, blank=True, null=True)                  # 1. อาจารย์ผู้สอน
    subject = models.ForeignKey(Subject)                                        # 2. วิชา
    section = models.ForeignKey(Section)                                        # 3. section
    termChoices = (
        ('', 'กรุณาเลือกภาคเรียน'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
    )
    term    = models.CharField(max_length=1, choices=termChoices, default='')   # 4. ภาคเรียน
    year    = models.CharField(max_length=4, default='')                        # 5. ปีการศึกษา

class HourlyEmployee(models.Model):
    user = models.OneToOneField(UserProfile)                                    # 1. UserProfile
    numberTaxpayment = models.CharField(max_length=20, blank=True, default="")  # 2. เลขประจำตัวผู้เสียภาษี
    status = models.CharField(max_length=50, blank=True, default="")            # 3. ตำแหน่ง
    employmentRate = models.FloatField(max_length=10, default=0.0)              # 4. อัตรารายได้

    def __unicode__(self):
        return self.user.firstname_en + " " + self.user.lastname_en

class Work(models.Model):
    releaseDate = models.DateField(auto_now=True)                               # 1. วันที่เพิ่มข้อมูล
    startTime = models.TimeField()                                              # 2. เวลาเริ่มทำงาน
    endTime = models.TimeField()                                                # 3. เวลาเลิกงาน
    note = models.TextField(blank=True)                                         # 4. หมายเหตุ
    employee = models.ForeignKey(HourlyEmployee)                                # 5. เป็นของพนักงานคนใด
    day = models.DateTimeField(auto_now=True)
    class meta:
        unique_together = ('employee', 'id')
        
    def get_time_diff(self):
        if (int(str(self.startTime.hour)) == 12) and ( int(str(self.endTime.hour)) > 12 ):
            diff_min = int(str(self.endTime.minute)) - 0    # calculate differ value of come_time
            diff_hour = int(str(self.endTime.hour)) - 13
        elif (int(str(self.startTime.hour)) < 12) and ( int(str(self.endTime.hour)) == 12 ):
            diff_min = 0 - int(str(self.startTime.minute))   # calculate differ value of come_time
            diff_hour = int(str(self.endTime.hour)) - int(str(self.startTime.hour))  # calculate differ value of back_time
        elif (int(str(self.startTime.hour)) == 12) and ( int(str(self.endTime.hour)) == 12 ):
            diff_min = 0
            diff_hour = 0
        else:
            diff_min = int(str(self.endTime.minute)) - int(str(self.startTime.minute))   # calculate differ value of come_time
            diff_hour = int(str(self.endTime.hour)) - int(str(self.startTime.hour))   # calculate differ value of back_time
        
        if diff_min < 0:
            diff_min = 60 + diff_min
            diff_hour = diff_hour - 1
        try:
            if (int(str(self.endTime.hour)) > 12) and (int(str(self.startTime)) !=12):
                diff_hour = diff_hour - 1
        except:
            pass
        if (diff_min < 10):
           return str(diff_hour) + ':0'+str(diff_min)
        else:
            return str(diff_hour) + ':'+str(diff_min)

templates/group3/add_hour.html
{% extends "base.html" %}

{% block title %}เพิ่มข้อมูล อาจารย์สองภาษา{% endblock %}

{% block pageHeader %}
<h2>เพิ่มข้อมูล <small>อาจารย์สองภาษา</small></h2>
<ol class="breadcrumb">
    <li><a href="{% url 'login:menu' %}">เมนู</a></li>
    <li><a href="{% url 'group3:hour_index' %}">ระบบพนักงานรายชั่วโมง</a></li>
    <li class="active">เพิ่มข้อมูลพนักงานรายชั่วโมง</li>
</ol>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form class="form-horizontal" method="post" action="{%url 'group3:add_hour_note' work_obj.id%}"> {% csrf_token %}
              <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">หมายเหตุ</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" placeholder="Text input" name="input_note_hour">
                </div>
              </div>
              <div class="form-group"> 
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-default" href="#">OK</button>
                </div>
              </div>
            </form>
        </div>
    </div>
            
{% endblock %}

templates/group3/hour_profile.html
{% extends "base.html" %}
{% block title %}Menu เมนู{% endblock %}
{% block pageHeader %}<h1>ระบบ<small> พนักงานรายชั่วโมง</small></h1>
<ol class="breadcrumb">
    <li><a href="{% url 'login:menu' %}">เมนู</a></li>
    <li><a href="{% url 'group3:hour_index' %}">ค้นหา</a></li>
    <li class="active">ระบบพนักงานรายชั่วโมง</li>
</ol>
{% endblock %}
{% block content %}
<div class="row">
    <div class="container-fluid">
        <div class="col-md-3">
            <!--a class="btn btn-primary btn-block {{status_on}}" href="{% url 'group3:add_hour_date' employObj.id %}" ><span class="glyphicon glyphicon-plus"></span> บันทึกเเวลาเข้าทำงาน </a>
            <a class="btn btn-primary btn-block {{status_off}}" href="{% url 'group3:add_hour_date2' employObj.id %}"><span class="glyphicon glyphicon-plus"></span> บันทึกเเวลาออกทำงาน </a-->
            <a class="btn btn-primary btn-block" href="{% url 'group3:add_work' employObj.id %}"><span class="glyphicon glyphicon-plus"></span> บันทึกเวลาทำงาน </a>
            <a class="btn btn-default btn-block" href="{% url 'group3:hourpdf' employObj.id scan_month scan_year%}" target = _blank><span class="glyphicon glyphicon-print"></span> พิมพ์ข้อมูล </a>
            <a class="btn btn-default btn-block" href="{% url 'group3:hour_index' %}" ><span class="glyphicon glyphicon-arrow-left"> ย้อนกลับ</span></a>
            <a class="btn btn-default btn-block" href="{% url 'group3:choose_work' employObj.id%}" ><span class="glyphicon glyphicon-calendar"> เลือกเวลา </span></a>

        </div> <p>{{check}}</p>
        <div class="col-md-9">
            <div class="row">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped">
                        <tr>
                            <th>ชื่อ-นามสกุล</th>
                            <td>{{name_th}} {{last_th}}</td>
                        </tr>
                        <tr>
                            <th>Name</th>
                            <td>{{name_en}} {{last_en}}</td>
                        </tr>
                        <tr>
                            <th>ภาควิชา</th>
                            <td>{{department}}</td>
                        </tr>
                        <tr>
                            <th>คณะ</th>
                            <td>{{faculty}}</td>
                        </tr>
                        <tr>
                            <th>เบอร์โทรศัพท์</th>
                            <td>{{tel}}</td>
                        </tr>
                    </table>
                </div>
            </div>

            {% if ListWork %}
                <div class="row">
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>วัน</th>
                                <th>วันที่ เดือน ปี</th>
                                <th>เวลาทำงาน</th>
                                <th>รวมชั่วโมง</th>
                                <th>หมายเหตุ</th>
                                <th>เมนู</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for working in ListWork %}
                            <tr>
                                <td data-title="วัน">
                                    {% ifequal working.day|date:"l" "Monday" %}จันทร์{%endifequal%}
                                    {% ifequal working.day|date:"l" "Tuesday" %}อังคาร{%endifequal%}
                                    {% ifequal working.day|date:"l" "Wednesday" %}พุธ{%endifequal%}
                                    {% ifequal working.day|date:"l" "Thursday" %}พฤหัสบดี{%endifequal%}
                                    {% ifequal working.day|date:"l" "Friday" %}ศุกร์{%endifequal%}
                                    {% ifequal working.day|date:"l" "Saturday" %}เสาร์{%endifequal%}
                                    {% ifequal working.day|date:"l" "Sunday" %}อาทิตย์{%endifequal%}
                                </td>
                                <td data-title="วันที่ เดือน ปี">{{working.releaseDate|date:"j"}}
                                
                                    {% ifequal working.releaseDate|date:"F" "January" %} มกราคม {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "February" %} กุมภาพันธ์ {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "March" %} มีนาคม {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "April" %} เมษายน {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "May" %} พฤษภาคม {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "June" %} มิถุนายน {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "July" %} กรกฎาคม {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "August" %} สิงหาคม {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "September" %} กันยายน {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "October" %} ตุลาคม {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "November" %} พฤศจิกายน {%endifequal%}
                                    {% ifequal working.releaseDate|date:"F" "December" %} ธันวาคม {%endifequal%}
                                    
                                                                                                พ.ศ. {{working.releaseDate|date:"Y"|add:"543" }}
                        
                                </td>
                                <td data-title="เวลาทำงาน">{{working.startTime|time:"H.i"}} น.{% if working.endTime|time:"H.i" != '00.00' %} - {{working.endTime|time:"H.i"}} น.{% endif %}</td>
                                <td data-title="รวมชั่วโมง">{{working.get_time_diff}}</td>
                                <td data-title="หมายเหตุ">{{working.note}}</td>
                                <td data-title="เมนู">
                                    <a class="btn btn-info btn-xs" href="{% url 'group3:add_hour_page' working.id%}">เพิ่ม/แก้ไขหมายเหตุ </a>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            {% else %}
                <div class="alert alert-warning" role="alert">ไม่มีข้อมูลสำหรับรายการนี้</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/group3/prof2lang_index.html
{% extends "base.html" %}
{% block head %}
    <style>

    </style>
{% endblock %}

{% block title %}ระบบอาจารย์สองภาษา{% endblock %}

{% block pageHeader %}
<h2>ระบบ <small>อาจารย์สองภาษา</small></h2>
<ol class="breadcrumb">
    <li><a href="{% url 'login:menu' %}">เมนู</a></li>
    <li class="active">ระบบอาจารย์สองภาษา</li>
</ol>
{% endblock %}

{% block content %}
    <!-- check has Prof2Lang object -->
        <div class="row">
            <div class="container-fluid">
                <div class="col-md-3">
                    <a class="btn btn-primary btn-block" href="{% url 'group3:prof2lang_add' 0 %}"><span class="glyphicon glyphicon-plus"></span> เพิ่มข้อมูล</a>
                    <a class="btn btn-default btn-block" href="{% url 'group3:genallpdf'%}" target = _blank><span class="glyphicon glyphicon-print"></span> พิมพ์ข้อมูล</a>
                    <a class="btn btn-success btn-block" href="{% url 'group3:prof_index' %}"><span class="glyphicon glyphicon-info-sign"></span> อาจารย์ผู้สอนทั้งหมด</a>
                </div>
                <div class="col-md-9">
                    {% if teachList %}
                        <div class="table-responsive">
                            <table class="table table-hover table-bordered table-striped" id="no-more-tables">
                                <thead>
                                <tr class="success">
                                    <th><a href="{% url 'group3:prof2lang_sort' 'fullname' %}">ชื่อ-สกุล</a></th>
                                    <th><a href="{% url 'group3:prof2lang_sort' 'prof__shortName' %}">ตัวย่อชื่อ</a></th>
                                    <th><a href="{% url 'group3:prof2lang_sort' 'subject__subjectID' %}">รหัสวิชา</a></th>
                                    <th><a href="{% url 'group3:prof2lang_sort' 'subject__subjectName' %}">ชื่อวิชา</a></th>
                                    <th>ตอนเรียน</th>
                                    <th>ภาคเรียน</th>
                                    <th>ปีการศึกษา</th>
                                    <th>เมนู</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for teach in teachList %}
                                <tr>
                                    <td data-title="ชื่อ-สกุล">
                                        {% ifequal teach.prof.academic_position "0"%}
                                            {% if teach.prof.prefix_name == "3" %}ดร.
                                            {% else %}อ.
                                            {% endif%}
                                        {% endifequal %}
                                        {% ifequal teach.prof.academic_position "1"%}ผู้ช่วยศาสตราจารย์{% ifequal teach.prof.prefix_name "3" %} ดร.{% endifequal %}{% endifequal %}
                                        {% ifequal teach.prof.academic_position "2"%}รองศาสตราจารย์{% ifequal teach.prof.prefix_name "3" %} ดร.{% endifequal %}{% endifequal %}
                                        {% ifequal teach.prof.academic_position "3"%}ศาสตราจารย์{% ifequal teach.prof.prefix_name "3" %} ดร.{% endifequal %}{% endifequal %}
                                        
                                        {{ teach.prof.firstName }}&ensp;{{ teach.prof.lastName }}</td>
                                    <td data-title="ตัวย่อ">{{ teach.prof.shortName }}</td>
                                    <td data-title="รหัสวิชา">{{ teach.subject.subjectID }}</td>
                                    <td data-title="ชื่อวิชา">{{ teach.subject.subjectName }}</td>
                                    <td data-title="ตอนเรียน">{{ teach.section.section }}</td>
                                    <td data-title="ภาคเรียน" align="center">{{ teach.term }}</td>
                                    <td data-title="ปีการศึกษา" align="center">{{ teach.year }}</td>
                                    <td data-title="เมนู">
                                        <a class="btn btn-info btn-xs" href="{% url 'group3:prof2lang_view' teach.id %}">ดูข้อมูล</a>
                                        <a class="btn btn-default btn-xs" href="{% url 'group3:genpdf' teach.id %}" target = _blank><span class="glyphicon glyphicon-print"></span></a>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div><!-- /table-responsive -->
                    {% else %}
                        <div class="alert alert-warning" role="alert">
                            <strong>ยังไม่มีข้อมูล!</strong> กรุณา
                            <a class="alert-link" href="{% url 'group3:prof2lang_add' 0 %}">เพิ่มข้อมูล</a>
                        </div>
                    {% endif %}
                </div><!-- /col-md-9 -->
            </div><!-- /container-fluid -->
        </div><!-- /row -->

{% endblock %}